[origin]
branch = "main"
last_commit_hash = "848f566ef4288ac2b71c3a8f236913fa29c647d5"
name = "TEMPLATE_NAME_TO_RESOLVE"
remote_url = "https://codeberg.org/wini/wini-template"

# All the paths are relatives to `./src` by default. At the exception of `modules`.
[path]
components = "./components"
cron = "./cron"
layouts = "./layouts"
pages = "./pages"
public = "../public"
# Modules is relative to `public`, because it should always be public.
modules = "./modules"

# The cache rules for the cache categories.
# > Note that each cache category (html, css, javscripts, public, or more if defined in
# `./src/shared/wini/cache.rs`), should have a cache rule associated to it in all environments.
#
# cache.default: Will be applied to every environment. (`./src/shared/wini/env.rs`)
# cache.xxxxxxx: (with *xxxxxxx* being a type of environment) Will overwrite cache.default if 
# the server is running under that environment.
# cache.xxxxxxx.function: Should function marked as "#[cache]", be cached ?
#
# More info about cache: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
[cache.default]
css = "public, max-age=3600"
function = true
html = "public, max-age=3600"
javascript = "public, max-age=3600"
public = "public, max-age=86000, immutable"
[cache.local]
css = "no-cache"
function = false
html = "no-cache"
javascript = "no-cache"
public = "no-cache"
